server:
  port: 8084
  servlet:
    context-path: /match-contract

spring:
  application:
    name: match-contract-service
  config:
    import: env.properties
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  services:
    match: http://localhost:8085/match

