server:
  port: 8083
  servlet:
    context-path: /invitation

spring:
  application:
    name: invitation-service

app:
  services:
    online-user: http://localhost:8086/online-user
    match: http://localhost:8085/match

