server:
  port: 8088
  servlet:
    context-path: /queue

spring:
  application:
    name: queue-service
  config:
    import: env.properties
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  services:
    profile: http://localhost:8087/profile
    match-contract: http://localhost:8084/match-contract

