server:
  port: 8087
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service
  neo4j:
    uri: ${DB_URL}
    authentication:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  config:
    import: env.properties



