server:
  port: 8080

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: chat-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=2
        - id: invitation-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/invitation/**
          filters:
            - StripPrefix=2
        - id: match-contract-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/match-contract/**
          filters:
            - StripPrefix=2
        - id: match-service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/match/**
          filters:
            - StripPrefix=2
        - id: online-user-service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/online-user/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/profile/profiles/**
          filters:
            - StripPrefix=2
        - id: queue-service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/queue/**
          filters:
            - StripPrefix=2