server:
  port: 8085
  servlet:
    context-path: /match

spring:
  application:
    name: match-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  config:
    import: env.properties
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  services:
    profile: http://localhost:8087/profile

