server:
  port: 8085
  servlet:
    context-path: /match

spring:
  application:
    name: match-service
  config:
    import: env.properties
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    mongodb:
      uri: ${DB_URL}

app:
  services:
    profile: http://localhost:8087/profile

